MODEL_DIR: "/srv/share/svanga3/bert-representations/"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets"
TRAIN:
    NUM_UPDATES_PER_TASK: 2000
    CHECKPOINT_INTERVAL: 1000
TASK:
    MULTITASK_STRATEGY: "EQUAL_SEQUENTIAL"
    TASKS:
        - mnli
        - sst_2