DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets/"
TRAIN:
    NUM_UPDATES_PER_TASK: 6000
    CHECKPOINT_INTERVAL: 3000
    EVAL_STEPS: 3000
    BATCH_SIZE: 32
    # DO_VAL: False
TASK:
    TASKS:
        - pos
