MODEL_DIR: "/srv/share/svanga3/bert-representations/"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets/"
TRAIN:
    NUM_EPOCHS_PER_TASK: 3
    CHECKPOINT_INTERVAL: 390
TASK:
    TASKS:
        - pos
        - sst_2
    MULTITASK_STRATEGY: "ROUND_ROBIN"