MODEL_DIR: "/srv/share/svanga3/bert-representations/"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets/"
TRAIN:
    NUM_UPDATES_PER_TASK: 1000
    CHECKPOINT_INTERVAL: 500
TASK:
    TASKS:
        - pos
        - sst_2
    MULTITASK_STRATEGY: "EQUAL_SEQUENTIAL"
MODEL:
    HEAD_FIRST_LAYERS: 0