TRAIN:
    NUM_UPDATES_PER_TASK: 6000
    CHECKPOINT_INTERVAL: 3000
TASK:
    TASKS:
        - mnli
        - pos
        - sts_b
        - sst_2
    MULTITASK_STRATEGY: "EQUAL_SEQUENTIAL"
MODEL:
    HEAD_FIRST_LAYERS: 2
    HEAD_BRANCHES:
        - [mnli]
        - [pos, sst_2]
        - [sts_b]