TRAIN:
    NUM_UPDATES_PER_TASK: 6000
    CHECKPOINT_INTERVAL: 3000
TASK:
    TASKS:
        - sts_b
        - mnli
        - sst_2
        - pos
    MULTITASK_STRATEGY: "EQUAL_SEQUENTIAL"
MODEL:
    HEAD_FIRST_LAYERS: 2
    HEAD_BRANCHES:
        - [mnli, sts_b]
        - [sst_2]
        - [pos]