TRAIN:
    NUM_UPDATES_PER_TASK: 2000
    CHECKPOINT_INTERVAL: 2000
    UPDATE_SEQUENCE: [1, 10]
    BATCH_SIZE: 32 # We're OOM-ing for some reason
TASK:
    MULTITASK_STRATEGY: "FIXED_SEQUENTIAL"
    TASKS:
        - sst_2
        - mnli