MODEL_DIR: "/srv/share/svanga3/bert-representations/"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets"
TRAIN:
    NUM_EPOCHS_PER_TASK: 1
    # NUM_UPDATES_PER_TASK: 20
    CHECKPOINT_INTERVAL: 2000
    # EVAL_STEPS: 5
TASK:
    TASKS:
        - sts_b
        - sst_2
    MULTITASK_STRATEGY: "ROUND_ROBIN"