MODEL_DIR: "/srv/share/svanga3/bert-representations/"
MODEL:
    BASE: "bert-base-cased"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/glue_data/STS-B"
TRAIN:
    NUM_EPOCHS_PER_TASK: 3
    LR_INIT: 2e-5
    EVAL_STEPS: 180
    BATCH_SIZE: 8
TASK:
    TASKS:
        - sts_b
