SEED: 1
MODEL_DIR: "/srv/share/svanga3/bert-representations/"
DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets/"
TRAIN:
    NUM_UPDATES_PER_TASK: 1000
    CHECKPOINT_INTERVAL: 200
TASK:
    TASKS:
        - sts_b
        - pos
    MULTITASK_STRATEGY: "EQUAL_SEQUENTIAL"