DATA:
    DATAPATH: "/srv/share/svanga3/bert-representations/all_datasets"
TRAIN:
    CHECKPOINT_INTERVAL: 2000
    EVAL_STEPS: 2000
    NUM_EPOCHS_PER_TASK: 1
TASK:
    TASKS:
        - sst_2
        - pos
        - sts_b
MODEL:
    HEAD_FIRST_LAYERS: 1
    HEAD_BRANCHES:
        - [sst_2, pos]
        - [sts_b]